### ISSUE TITLE
2.1.40_sync_error_no_attribute_basicCheck

### ISSUE THREAD

**Issue by dobefore** [ankicommunity/anki-sync-server#73]
Anki desktop:2.1.40
OS:Win10
anki:2.1.40
once installed,I started anki , input account and hit sync.
```
 File "C:\Users\Admin\Desktop\ANKI-S~1\ANKI_S~1.36\ankisyncd\sync_app.py", line 588, in _execute_handler_method_in_thread
    result = thread.execute(run_func, kw=keyword_args)
  File "C:\Users\Admin\Desktop\ANKI-S~1\ANKI_S~1.36\ankisyncd\thread.py", line 79, in execute
    raise ret
  File "C:\Users\Admin\Desktop\ANKI-S~1\ANKI_S~1.36\ankisyncd\thread.py", line 98, in _run
    ret = self.wrapper.execute(func, args, kw, return_queue)
  File "C:\Users\Admin\Desktop\ANKI-S~1\ANKI_S~1.36\ankisyncd\collection.py", line 45, in execute
    ret = func(*args, **kw)
  File "C:\Users\Admin\Desktop\ANKI-S~1\ANKI_S~1.36\ankisyncd\sync_app.py", line 579, in run_func
    res = handler_method(**keyword_args)
  File "C:\Users\Admin\Desktop\ANKI-S~1\ANKI_S~1.36\ankisyncd\sync_app.py", line 138, in sanityCheck2
    server = self.sanityCheck(full)
```

```
  File "C:\Users\Admin\Desktop\ANKI-S~1\ANKI_S~1.36\ankisyncd\sync.py", line 77, in sanityCheck
    if not self.col.basicCheck():
AttributeError: 'Collection' object has no attribute 'basicCheck'
[2021-02-11 21:05:05,624]:INFO:ankisyncd.http:127.0.0.1 "POST /sync/sanityCheck2 HTTP/1.0" 500 59
[2021-02-11 21:05:05,629]:INFO:ankisyncd.http:127.0.0.1 "POST /sync/abort HTTP/1.0" 404 154
```

**Comment by zimhat** [comment]
I have the same error

**Comment by junyixu** [comment]
@dobefore python3.9?

it confuse me,  ">=3.8" in poetry.lock

I had the same error, but when I use python 3.8, it works.

**Comment by senorsmile** [comment]
I'm on desktop 2.1.35 and I get the same error.

**Comment by senorsmile** [comment]
I noticed that the initial upload works fine, but subsequent syncs fail. 

I tried another device.  It prompted to download the initial stuff since it was a brand new anki install.  The initial sync (download only) worked fine, but the subsequent sync after doing a single review produced the same error in the logs. 


I have a dockerfile for previous builds I use on an old ubuntu 16.04 machine.  I tried it with 2.1.33 and got the exact same results.  I will build a few older versions to see if I notice any changes.

**Comment by senorsmile** [comment]
I just tested it on 2.1.20 desktop version and I see the same error.

**Comment by senorsmile** [comment]
on this page it says the latest version "supported" is 2.1.19: https://github.com/ankicommunity/anki-devops-services/tree/develop/services/anki-sync-server/images

The last packaged release is 2.1.15, so I tried that.  I get the same error in the server logs: 
`AttributeError: 'Collection' object has no attribute 'basicCheck'
`

**Comment by senorsmile** [comment]
I went back to anki-sync-server 2.2.0 and tested against anki desktop 2.1.15.  I suspect there is something up in master.

**Comment by junyixu** [comment]
It works with python3.8;
Same error with python3.9

**Comment by senorsmile** [comment]
interesting.  I'm using asdf to use python 3.8.7 as well as a Pipfile calling out 3.8.  I wonder if core python 3.9 (part of my manjaro installation) is "leaking through".  I'll test on a 3.8 Dockerfile to double check.

**Comment by senorsmile** [comment]
I'm seeing the same error doing a rebuild using this dockerfile: https://github.com/ankicommunity/anki-devops-services/blob/develop/services/anki-sync-server/images/Dockerfile

replacing both instances of 3.9 with 3.8

**Comment by zimhat** [comment]
@junyixu I am on python 3.8.5, never installed 3.9 (Ubuntu server 20.04) and I still get that error

**Comment by junyixu** [comment]
@zimhat It works on python 3.8.7 for me using pyenv

**Comment by senorsmile** [comment]
@junyixu which OS and version are you running on?
Are you on latest master or develop branch? (i've tried both).  
which version of the desktop app are you using?

Did you simply do `pyenv global 3.8.7` followed by a `pip install -r src/requirements.txt`?

**Comment by junyixu** [comment]
@senorsmile I run the anki-sync-server on archlinux(a vps);
master;
2.1.40 for windows and 2.1.35 for  arch linux desktop;
```
$ pyenv install 3.8.7
$ cd anki-sync-server
$ pyenv local 3.8.7
$ pyenv virtualenv anki-server
$ pyenv activate anki-server 
$ pip install -r src/requirements.txt
```

**Comment by zimhat** [comment]
I find it hard to believe that it would be only compatible with python 3.8.7. If so, it will be a hassle for any new setup. Any idea about what could have introduced this bug ?

**Comment by sunnysab** [comment]
> 
> 
> @zimhat It works on python 3.8.7 for me using pyenv

It's a bad news that I tried the method but it still failed.  :-(

![QQ截图20210223115118](https://user-images.githubusercontent.com/11255727/108800228-8b417380-75cd-11eb-8549-29d8d346341d.png)

**Comment by junyixu** [comment]
@sunnysab `/data`?
I didn't use docker.

**Comment by sunnysab** [comment]
> 
> 
> @sunnysab `/data`?
> I didn't use docker.
> 
> Just a normal user rather than root.
> Simply git clone it to `~` and cd anki-sync-server

Well, I've used docker before, so I named the directory `/data`...
Unfortunately, I created a normal user and copy the directory to home but failed again.

So I see you mentioned  to re-clone. I did that again and this time it worked. I'm so happy.
I tried to diff `src` in two version. It seems like only data / db file different.

My experience is : I've been used python 3.9 and yesterday I try to re-install my Linux. After I restore my backup of anki directory I encountered the problem (This time is a python 3.8.5). 
I think it's a data processing issue, not caused by python version.

**Comment by chewblacka** [comment]
I have python 3.8.7 installed by default on OpenSUSE tumbleweed, and I'm getting the same error both with linux and windows clients of anki 2.1.40

**Comment by sunnysab** [comment]
Oh, my god. Yesterday (18 hours ago) I finished configration.

But currently it is going wrong again.

**Comment by zimhat** [comment]
Another information : If I force sync in one direction and do a full upload to anki server, the upload succeeds. That's what I do each time I want to sync now. Obviously, it's not ideal.

**Comment by chewblacka** [comment]
Ok my native python is 3.8, so I tried running in a python 3.9 docker container and everything works. No error.

**Comment by senorsmile** [comment]
I went back to the feb 3, 2020 commit: https://github.com/ankicommunity/anki-sync-server/commit/41205c0b92290bc3dc6e50d401dc9dbf33bdd52c

This only works with <= 2.1.19.  I tested with 2.1.15.  This commit fully works. 

I tried a few other commits after that until I got to aug 26, 2020: https://github.com/ankicommunity/anki-sync-server/commit/8358b092a3b119585286dfabfcd2ae0195cffa45

This was the first commit I found that reproduce the `object has not attribute 'basicCheck'` error. 

https://github.com/ankicommunity/anki-sync-server/commit/8358b092a3b119585286dfabfcd2ae0195cffa45

**Comment by chewblacka** [comment]
I installed python3.9 on my native machine and that works 100% fine too. So for me the error is limited to python 3.8 and is solved by installing 3.9.

**Comment by smartlitchi** [comment]
@senorsmile thanks to your investigation, I went to check the commits on that day. It seems that this commit https://github.com/ankicommunity/anki-sync-server/commit/d0f7d05b446789bcd11542d6472ae4f54fe23d3e introduced the `self.col.basicCheck()` that causes the error we are seeing.

**Comment by liu-hz** [comment]
When I was testing the version of anki2.1.41, I encountered the following problem: "nontype" object is not subsertable
![@V1`PPNN 6$A}SPI9_`ZTS3](https://user-images.githubusercontent.com/71445465/109927601-6ea8e800-7cff-11eb-83ea-aa0cfd595939.png)

**Comment by liu-hz** [comment]
if i delete this self.remove(graves) i can get the same error AttributeError: 'Collection' object has no attribute 'basicCheck'。Put that  code it can't be show .but show the anther error like my show that nontyp . how to fix it ,i use the desktop 2.1.41

**Comment by dobefore** [comment]
As a result, [this commit repo](https://github.com/ankicommunity/anki-sync-server/tree/5e56a2edcd68cf4ad2a585329529ba0764d8d47d)  which was committed by cecini works.

**Comment by senorsmile** [comment]
> As a result, [this commit repo](https://github.com/ankicommunity/anki-sync-server/tree/5e56a2edcd68cf4ad2a585329529ba0764d8d47d) which was committed by cecini works.Yet,this version is not available in 2.1.41.

I have confirmed that this link works.  I have tested it against 2.1.40.  I was unable to get it to work on 2.1.35. 

I did notice that at first I would get different errors.  After doing a database check and forcing upload, everything works normally afterwards.

**Comment by dobefore** [comment]
#84

**Comment by dobefore** [comment]
#87

**Comment by VikashKothary** [comment]
I've merged @dobefore's PR. Thanks for that. This was a common issue and it's good to see it fixed. Can someone test to confirm it's working for them?
