### ISSUE TITLE
Test fail with anki 2.1.49

### ISSUE THREAD

**Issue by ohdearaugustin** [ankicommunity/anki-sync-server#124]
The test only work with anki 2.1.43. It seems the dependencies got updated but not tested.

Tested with python 3.10.1

Steps:
 - make init
 - make tests
 
Output:
```
..ENeither session_db_path nor session_manager set, ankisyncd will lose sessions on application restart
.......E..............neither auth_db_path nor user_manager set, ankisyncd will accept any password
.E
======================================================================
ERROR: test_media (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_media
Traceback (most recent call last):
  File "/usr/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/augustin/programming/anki-sync-server/tests/test_media.py", line 6, in <module>
    import helpers.collection_utils
  File "/home/augustin/programming/anki-sync-server/tests/helpers/collection_utils.py", line 6, in <module>
    from anki import Collection
ImportError: cannot import name 'Collection' from 'anki' (/home/augustin/programming/anki-sync-server/.venv/lib/python3.10/site-packages/anki/__init__.py)


======================================================================
ERROR: test_meta (test_sync_app.SyncCollectionHandlerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/augustin/programming/anki-sync-server/tests/test_sync_app.py", line 64, in test_meta
    meta = self.syncCollectionHandler.meta(v=SYNC_VER)
  File "/home/augustin/programming/anki-sync-server/src/ankisyncd/sync_app.py", line 100, in meta
    'scm': self.col.scm,
  File "/home/augustin/programming/anki-sync-server/.venv/lib/python3.10/site-packages/anki/_legacy.py", line 52, in __getattr__
    raise AttributeError
AttributeError

======================================================================
ERROR: test_web_hostkey (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_web_hostkey
Traceback (most recent call last):
  File "/usr/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/augustin/programming/anki-sync-server/tests/test_web_hostkey.py", line 2, in <module>
    from sync_app_functional_test_base import SyncAppFunctionalTestBase
  File "/home/augustin/programming/anki-sync-server/tests/sync_app_functional_test_base.py", line 8, in <module>
    from helpers.collection_utils import CollectionUtils
  File "/home/augustin/programming/anki-sync-server/tests/helpers/collection_utils.py", line 6, in <module>
    from anki import Collection
ImportError: cannot import name 'Collection' from 'anki' (/home/augustin/programming/anki-sync-server/.venv/lib/python3.10/site-packages/anki/__init__.py)


----------------------------------------------------------------------
Ran 27 tests in 0.030s

FAILED (errors=3)
make: *** [Makefile:23: tests] Error 1
```
1. Fix     Change `from anki import Collection ` in tests/helpers/collection_utils.py to `from anki.collection import Collection`
2. I have no idea to fix the error with the collition.scm return

Short workaround  `poetry add anki="2.1.43"`

**Comment by VikashKothary** [comment]
Thanks for raising this. I've made the first change as you're stated so hopefully we're a step closer to getting working tests.
